name: Zonn
options:
  bundleIdPrefix: com.sultanvaliyev
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"

targets:
  Zonn:
    type: application
    platform: macOS
    sources:
      - path: Zonn
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.sultanvaliyev.Zonn
        PRODUCT_NAME: Zonn
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Zonn/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_ENTITLEMENTS: Zonn/Zonn.entitlements
        ENABLE_HARDENED_RUNTIME: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: Zonn/Info.plist
      properties:
        LSUIElement: true
        NSHighResolutionCapable: true
        CFBundleName: Zonn
        CFBundleDisplayName: Zonn
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
